# Generated by Django 4.0.1 on 2022-01-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_author_book_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
