# Generated by Django 4.0.1 on 2022-01-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checkout',
        ),
    ]
