# Generated by Django 4.0.1 on 2022-01-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=200)),
                ('post_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
