# Generated by Django 4.0.1 on 2022-01-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0003_alter_chirp_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chirp',
            old_name='user',
            new_name='username',
        ),
    ]
