# Generated by Django 4.0.1 on 2022-01-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0004_rename_user_chirp_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
