# Generated by Django 4.0.1 on 2022-01-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='person_city.city'),
        ),
        migrations.AddField(
            model_name='person',
            name='favorite_colors',
            field=models.ManyToManyField(to='person_city.Color'),
        ),
    ]
