# Generated by Django 4.0.1 on 2022-01-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lived_in_states',
            field=models.ManyToManyField(to='census.State'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='census.state'),
        ),
    ]
