# Generated by Django 4.0.3 on 2022-03-21 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_posts_created_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
