# Generated by Django 4.0.1 on 2022-01-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chirp',
            old_name='title',
            new_name='body',
        ),
    ]
