# Generated by Django 4.0.1 on 2022-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_alter_groceryitem_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
