# Generated by Django 4.0.1 on 2022-02-05 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery_list', '0004_groceryitem_user_alter_groceryitem_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groceries', to=settings.AUTH_USER_MODEL),
        ),
    ]
