# Generated by Django 4.0.1 on 2022-01-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(max_length=10)),
                ('completed_date', models.DateField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
