# Generated by Django 4.0.1 on 2022-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
