# Generated by Django 4.0 on 2022-01-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
